name: 🚀 Deploy website on push
on:
  push: 
    branches: [main]

jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using SSH 
      uses: appleboy/ssh-action@v0.5.0
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME}}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd /home/iwasim07/gitautomate/
          git pull origin main
          git status
        
